services:
  postgres:
    image: postgres
    container_name: bhts-postgres
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  server:
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  app_postgres_data:
